"""The target plugin boundary (ADR-0005).

A target receives the IR and returns files. It must not import
`orgagents.spec` — a test enforces that, which is what keeps permission
resolution from being re-derived (and re-derived differently) per target.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Callable, Optional, Protocol, runtime_checkable

from ..plugins import ProviderDescriptor, Registry
from .ir import SystemIR

#: Entry-point group a third-party deployment target registers under.
TARGET_GROUP = "orgagents.targets"

GENERATED_HEADER = (
    "Generated by orgagents from the system spec '{name}' "
    "(spec_version {spec_version}, ir {ir_version}).\n"
    "Do not edit: this file is regenerated on every compile. "
    "Put customizations in overlays/."
)


@dataclass
class GeneratedFile:
    """One artifact produced by a target."""

    path: str
    content: str
    executable: bool = False
    # Written once and then left alone (e.g. a sample env file).
    preserve_if_exists: bool = False
    # An engineer-owned file the compiler only ever ADDS to: on regeneration,
    # top-level `def`s already present are left exactly as the engineer left
    # them (implemented or not), and only defs the file is missing are appended.
    # A regeneration never rewrites or removes an implementation (ADR-0089).
    merge_additive: bool = False

    def with_header(self, ir: SystemIR, comment: str = "#") -> "GeneratedFile":
        header = GENERATED_HEADER.format(
            name=ir.name, spec_version=ir.spec_version, ir_version=ir.ir_version
        )
        prefix = "\n".join(f"{comment} {line}" for line in header.splitlines())
        return GeneratedFile(
            path=self.path,
            content=f"{prefix}\n\n{self.content}",
            executable=self.executable,
            preserve_if_exists=self.preserve_if_exists,
            merge_additive=self.merge_additive,
        )


@runtime_checkable
class Target(Protocol):
    """What every deployment target implements."""

    id: str

    def describe(self) -> dict[str, Any]: ...

    def generate(self, ir: SystemIR) -> list[GeneratedFile]: ...


#: What each built-in target can carry, in the shared vocabulary (ADR-0091).
#: A third-party target declares its own by exposing `descriptor()`.
_BUILTIN_SUPPORT: dict[str, set[str]] = {
    "local": {"instructions", "tools", "model", "subagents", "interrupt_on",
              "long_term_memory", "skills", "structured_output",
              "durable_execution", "streaming"},
    # Every terraform:<cloud> carries the same design facts; the cloud difference is
    # which resources they become, not what survives.
    "terraform": {"instructions", "tools", "model", "subagents",
                  "interrupt_on", "long_term_memory", "skills",
                  "structured_output", "durable_execution"},
    "maf": {"instructions", "tools", "model"},
    "adk": {"instructions", "tools", "model", "subagents",
            "structured_output"},
    "langgraph": {"instructions", "tools", "model", "subagents",
                  "interrupt_on", "skills", "long_term_memory",
                  "filesystem_permissions", "structured_output", "planning",
                  "middleware", "streaming", "durable_execution"},
}


def _descriptor_for(target: Target) -> Optional[ProviderDescriptor]:
    """A target's own descriptor if it publishes one, else the built-in table.

    Third-party targets are asked first, so a plugin is never described by a
    table it cannot edit.
    """
    own = getattr(target, "descriptor", None)
    if own is not None:
        return own() if callable(own) else own
    described = target.describe()
    supports = _BUILTIN_SUPPORT.get(
        target.id, _BUILTIN_SUPPORT.get(target.id.split(":")[0], set()))
    return ProviderDescriptor(
        id=target.id,
        title=described.get("title", target.id),
        kind="target",
        summary=described.get("summary") or described.get("emits", ""),
        supports=frozenset(supports),
    )


@dataclass
class TargetRegistry:
    """The deployment targets available, built-in and installed.

    A thin face over the shared plugin `Registry` (ADR-0091) so existing
    callers keep using `.targets`, `.register(target)` and `.ids()`.
    """

    registry: Registry = field(
        default_factory=lambda: Registry(name="target",
                                         entry_point_group=TARGET_GROUP))

    @property
    def targets(self) -> dict[str, Target]:
        return self.registry.items

    def register(self, target: Target, *, replace: bool = False) -> Target:
        return self.registry.register(
            target.id, target, descriptor=_descriptor_for(target),
            replace=replace)

    def register_factory(self, target_id: str,
                         factory: Callable[[], Target]) -> None:
        self.registry.register(target_id, factory(), replace=True)

    def get(self, target_id: str) -> Optional[Target]:
        return self.registry.get(target_id)

    def require(self, target_id: str) -> Target:
        return self.registry.require(target_id)

    def ids(self) -> list[str]:
        return self.registry.ids()

    def describe_all(self) -> list[dict[str, Any]]:
        return [t.describe() for _, t in sorted(self.registry.items.items())]

    def descriptors(self) -> list[dict[str, Any]]:
        return self.registry.describe_all()

    def supporting(self, feature: str) -> list[str]:
        return self.registry.supporting(feature)


REGISTRY = TargetRegistry()


def register_builtin_targets() -> TargetRegistry:
    """Register the targets that ship with the platform, then any installed.

    Loading the built-ins is guarded by a one-shot flag rather than "is the
    registry empty?", because the latter meant a caller who registered their
    own target first silently lost every built-in.
    """
    def _builtins() -> None:
        from .targets.adk import GoogleADKTarget
        from .targets.langgraph import LangGraphPlatformTarget
        from .targets.local import LocalTarget
        from .targets.maf import MicrosoftAgentFrameworkTarget
        from .targets.terraform import TerraformTarget

        REGISTRY.register(LocalTarget(), replace=True)
        for provider in ("gcp", "aws", "azure"):
            REGISTRY.register(TerraformTarget(provider), replace=True)
        # Platform targets rather than infrastructure ones: they emit
        # somebody else's agent definitions (ADR-0005).
        REGISTRY.register(MicrosoftAgentFrameworkTarget(), replace=True)
        REGISTRY.register(GoogleADKTarget(), replace=True)
        REGISTRY.register(LangGraphPlatformTarget(), replace=True)

    REGISTRY.registry.load_builtins(_builtins)
    # Installed plugins come after, and may not shadow a built-in silently.
    REGISTRY.registry.discover()
    return REGISTRY
