"""The target plugin boundary (ADR-0005).

A target receives the IR and returns files. It must not import
`orgagents.spec` — a test enforces that, which is what keeps permission
resolution from being re-derived (and re-derived differently) per target.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Callable, Optional, Protocol, runtime_checkable

from .ir import SystemIR

GENERATED_HEADER = (
    "Generated by orgagents from the system spec '{name}' "
    "(spec_version {spec_version}, ir {ir_version}).\n"
    "Do not edit: this file is regenerated on every compile. "
    "Put customizations in overlays/."
)


@dataclass
class GeneratedFile:
    """One artifact produced by a target."""

    path: str
    content: str
    executable: bool = False
    # Written once and then left alone (e.g. a sample env file).
    preserve_if_exists: bool = False

    def with_header(self, ir: SystemIR, comment: str = "#") -> "GeneratedFile":
        header = GENERATED_HEADER.format(
            name=ir.name, spec_version=ir.spec_version, ir_version=ir.ir_version
        )
        prefix = "\n".join(f"{comment} {line}" for line in header.splitlines())
        return GeneratedFile(
            path=self.path,
            content=f"{prefix}\n\n{self.content}",
            executable=self.executable,
            preserve_if_exists=self.preserve_if_exists,
        )


@runtime_checkable
class Target(Protocol):
    """What every deployment target implements."""

    id: str

    def describe(self) -> dict[str, Any]: ...

    def generate(self, ir: SystemIR) -> list[GeneratedFile]: ...


@dataclass
class TargetRegistry:
    targets: dict[str, Target] = field(default_factory=dict)

    def register(self, target: Target) -> Target:
        self.targets[target.id] = target
        return target

    def register_factory(self, target_id: str, factory: Callable[[], Target]) -> None:
        self.targets[target_id] = factory()

    def get(self, target_id: str) -> Optional[Target]:
        return self.targets.get(target_id)

    def ids(self) -> list[str]:
        return sorted(self.targets)

    def describe_all(self) -> list[dict[str, Any]]:
        return [t.describe() for _, t in sorted(self.targets.items())]


REGISTRY = TargetRegistry()


def register_builtin_targets() -> TargetRegistry:
    """Register the targets that ship with the platform."""
    from .targets.local import LocalTarget
    from .targets.adk import GoogleADKTarget
    from .targets.langgraph import LangGraphPlatformTarget
    from .targets.maf import MicrosoftAgentFrameworkTarget
    from .targets.terraform import TerraformTarget

    if not REGISTRY.targets:
        REGISTRY.register(LocalTarget())
        for provider in ("gcp", "aws", "azure"):
            REGISTRY.register(TerraformTarget(provider))
        # Platform targets rather than infrastructure ones: they emit
        # somebody else's agent definitions (ADR-0005).
        REGISTRY.register(MicrosoftAgentFrameworkTarget())
        REGISTRY.register(GoogleADKTarget())
        REGISTRY.register(LangGraphPlatformTarget())
    return REGISTRY
