"""The profile reference: one generated page per profile (ADR-0112).

`orgagents metamodel docs` writes `docs/metamodel/<profile>.md` for every
profile and `docs/metamodel/profiles.md` as their index, and regenerates the
PlantUML diagrams. Nothing here is hand-written documentation: every table and
diagram is read from the profile declarations, so the reference cannot drift
from the model, and a test fails when the committed pages are stale.
"""
from __future__ import annotations

from pathlib import Path
from typing import Callable

from . import (PROFILES, Profile, RelKind, profile_of, to_plantuml,
               to_plantuml_ownership, to_plantuml_profile)
from .uml import Relationship

HEADER = ("<!-- Generated by `orgagents metamodel docs` from "
          "src/orgagents/metamodel/. Do not edit: change the profile and "
          "regenerate. -->")


def page_name(profile: Profile) -> str:
    return f"{profile.name.lower()}.md"


def _cls(name: str) -> str:
    """A diagram-safe class name: stereotype kinds in CamelCase, DataType and
    Enumeration names as they are."""
    return "".join(p[:1].upper() + p[1:] for p in name.split("_"))


def _display(name: str) -> str:
    """How an element is named in prose: «Stereotype» or the type name."""
    p = profile_of(name)
    if p is not None:
        st = p.stereotype(name)
        if st is not None:
            return f"«{st.name}»"
    return name


def _esc(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def _rel_label(r: Relationship) -> str:
    kind = r.kind.value
    if r.stereotype and r.kind in (RelKind.ABSTRACTION,):
        return f"{kind} «{r.stereotype}»"
    return kind


_MERMAID = {
    RelKind.COMPOSITION: "*--",
    RelKind.AGGREGATION: "o--",
    RelKind.ASSOCIATION: "-->",
    RelKind.DEPENDENCY: "..>",
    RelKind.USAGE: "..>",
    RelKind.DEPLOYMENT: "..>",
    RelKind.ABSTRACTION: "..>",
    RelKind.REALIZATION: "..|>",
    RelKind.GENERALIZATION: "--|>",
}


def mermaid(profile: Profile) -> str:
    """The profile's class diagram. Elements of an imported profile appear
    as plain boxes named with their profile, so a page shows what it relies
    on without redrawing it."""
    lines = ["classDiagram", "  direction LR"]
    own = profile.element_names()
    shown: set[str] = set()

    def box(name: str) -> None:
        if name in shown:
            return
        shown.add(name)
        home = profile_of(name)
        cid = _cls(name)
        st = home.stereotype(name) if home else None
        if name in own:
            if st is not None:
                label = f"{st.name}"
                ann = (f"<<{st.extends.value}>>" if not st.abstract
                       else "<<abstract>>")
            elif home and home.enumeration(name):
                label, ann = name, "<<enumeration>>"
            elif home and home.datatype(name):
                label, ann = name, "<<dataType>>"
            else:
                label, ann = name, "<<associationClass>>"
            lines.append(f'  class {cid}["{label}"] {{')
            lines.append(f"    {ann}")
            for prop in profile.properties:
                if prop.owner == name:
                    lines.append(f"    {prop.name} : {prop.type} "
                                 f"[{prop.multiplicity}]")
            if home and home.enumeration(name):
                lines.extend(f"    {lit}"
                             for lit in home.enumeration(name).literals)
            lines.append("  }")
        else:
            label = (st.name if st is not None else name)
            where = home.name if home else "?"
            lines.append(f'  class {cid}["{where}::{label}"]')

    for name in sorted(own):
        box(name)
    for r in profile.relationships:
        if r.stereotype == "owns":
            continue            # ownership has its own diagram
        box(r.source)
        box(r.target)
        a, b = _cls(r.source), _cls(r.target)
        arrow = _MERMAID[r.kind]
        if r.kind in (RelKind.GENERALIZATION, RelKind.REALIZATION) \
                and not r.field:
            lines.append(f"  {a} {arrow} {b}")
            continue
        label = r.stereotype or r.field
        if r.kind is RelKind.ABSTRACTION:
            label = f"«{r.stereotype}»"
        mult = ""
        if r.kind in (RelKind.ASSOCIATION, RelKind.COMPOSITION):
            mult = f' "{r.source_mult}" {arrow} "{r.target_mult}" '
            lines.append(f"  {a}{mult}{b} : {label}")
        else:
            lines.append(f"  {a} {arrow} {b} : {label}")
    return "\n".join(lines) + "\n"


def profile_page(profile: Profile) -> str:
    out = [HEADER, "", f"# {profile.name} profile", ""]
    if profile.doc:
        out += [profile.doc, ""]
    imports = ", ".join(f"[{n}]({n.lower()}.md)" for n in profile.imports) \
        or "UML only"
    importers = [p.name for p in PROFILES if profile.name in p.imports]
    out += [f"- **Version:** {profile.version}",
            f"- **Imports:** {imports}",
            f"- **Imported by:** "
            + (", ".join(f"[{n}]({n.lower()}.md)" for n in importers)
               or "nothing"),
            f"- **Declares:** {len(profile.stereotypes)} stereotypes, "
            f"{len(profile.datatypes)} DataTypes, "
            f"{len(profile.enumerations)} enumerations, "
            f"{len(profile.relationships)} relationships, "
            f"{len(profile.properties)} properties", ""]

    out += ["## Class diagram", "", "```mermaid", mermaid(profile).rstrip(),
            "```", ""]

    if profile.stereotypes:
        out += ["## Stereotypes", "",
                "| Stereotype | Extends | Spec class | Lives in | Notes |",
                "|---|---|---|---|---|"]
        for s in profile.stereotypes:
            notes = []
            if s.abstract:
                notes.append("{isAbstract}")
            if not s.palette:
                notes.append("not on the palette")
            if s.doc:
                notes.append(_esc(s.doc))
            out.append(f"| «{s.name}» (`{s.kind}`) | {s.extends.value} | "
                       f"{f'`{s.model}`' if s.model else '—'} | "
                       f"{f'`{s.collection}`' if s.collection else '—'} | "
                       f"{'; '.join(notes)} |")
        out.append("")

    owners = sorted({p.owner for p in profile.properties},
                    key=lambda o: (profile_of(o) is not profile, o))
    if owners:
        out += ["## Properties", "",
                "| Owner | Property | Type | Multiplicity | Notes |",
                "|---|---|---|---|---|"]
        for o in owners:
            for prop in profile.properties:
                if prop.owner == o:
                    out.append(f"| {_display(o)} | `{prop.name}` | "
                               f"{prop.type} | {prop.multiplicity} | "
                               f"{_esc(prop.doc)} |")
        out.append("")

    if profile.datatypes:
        out += ["## DataTypes", "", "| DataType | Spec class | Meaning |",
                "|---|---|---|"]
        for d in profile.datatypes:
            out.append(f"| {d.name} | `{d.model}` | {_esc(d.doc)} |")
        out.append("")

    if profile.enumerations:
        out += ["## Enumerations", "",
                "| Enumeration | Literals | Spec enum | Meaning |",
                "|---|---|---|---|"]
        for e in profile.enumerations:
            lits = ", ".join(f"`{x}`" for x in e.literals)
            if e.uml:
                uml = dict(e.uml)
                lits = ", ".join(f"`{x}` ({uml[x]})" if x in uml else f"`{x}`"
                                 for x in e.literals)
            out.append(f"| {e.name} | {lits} | "
                       f"{f'`{e.model}`' if e.model else '*a named Literal*'}"
                       f" | {_esc(e.doc)} |")
        out.append("")

    rels = [r for r in profile.relationships if r.field or r.kind in (
        RelKind.GENERALIZATION, RelKind.REALIZATION)]
    if rels:
        out += ["## Relationships", "",
                "| Source | Relationship | Target | Multiplicity | Field | "
                "Constraint |", "|---|---|---|---|---|---|"]
        for r in rels:
            name = (f"{_rel_label(r)} «{r.stereotype}»"
                    if r.stereotype and r.kind is not RelKind.ABSTRACTION
                    else _rel_label(r))
            field = (f"`{r.owner_kind()}.{r.field}`" if r.field else "—")
            if r.association_class:
                field += f" ({r.association_class})"
            if r.selector:
                field += f" where `{r.selector[0]} = {r.selector[1]}`"
            out.append(f"| {_display(r.source)} | {name} | "
                       f"{_display(r.target)} | "
                       f"{r.source_mult} → {r.target_mult} | {field} | "
                       f"{_esc(r.constraint)} |")
        out.append("")
    return "\n".join(out)


def index_page() -> str:
    out = [HEADER, "", "# The OrgAgents profiles", "",
           "The platform's model is a set of UML profiles, one per concern "
           "(ADR-0101, ADR-0112). The profiles are authoritative for what "
           "the model means; `spec/model.py` and `spec/binding.py` realise "
           "them and are held equal to them by "
           "`tests/test_metamodel_completeness.py`. These pages and the "
           "`.puml` diagrams beside them are generated.", "",
           "| Profile | Imports | Stereotypes | DataTypes | Enumerations | "
           "Relationships | Properties |",
           "|---|---|---|---|---|---|---|"]
    for p in PROFILES:
        out.append(f"| [{p.name}]({page_name(p)}) | "
                   f"{', '.join(p.imports) or 'UML'} | "
                   f"{len(p.stereotypes)} | {len(p.datatypes)} | "
                   f"{len(p.enumerations)} | {len(p.relationships)} | "
                   f"{len(p.properties)} |")
    out += ["", "Whole-model diagrams: `orgagents-model.puml` (the spec "
            "profiles as one class diagram), `orgagents-profile.puml` "
            "(stereotypes extending metaclasses), `orgagents-ownership.puml` "
            "(composition from the root).", ""]
    return "\n".join(out)


def outputs() -> dict[str, Callable[[], str]]:
    """Every generated file under docs/metamodel, by name."""
    files: dict[str, Callable[[], str]] = {
        "profiles.md": index_page,
        "orgagents-model.puml": to_plantuml,
        "orgagents-profile.puml": to_plantuml_profile,
        "orgagents-ownership.puml": to_plantuml_ownership,
    }
    for p in PROFILES:
        files[page_name(p)] = (lambda p=p: profile_page(p))
    return files


def write(out: Path) -> list[Path]:
    out.mkdir(parents=True, exist_ok=True)
    written = []
    for name, render in outputs().items():
        path = out / name
        path.write_text(render(), encoding="utf-8", newline="\n")
        written.append(path)
    return written
