"""A third-party cloud for the Terraform target (ADR-0091).

Acme runs a private OpenStack cloud. Adding it is a `ProviderProfile` plus one
call — no edit to orgagents, and the target for it is then
`terraform:acme_cloud`, registered and bound like any built-in.

A profile is a set of **claims about what this cloud can express**, and the
honest ones are the fields that say what it *cannot*:

* `coarse_actions` names the neutral permission verbs this cloud's IAM cannot
  express at the granularity the design asked for. Anything listed here is
  granted *more broadly* than the spec intended, and the generated `MAPPING.md`
  says so under "Coarsened permissions" rather than letting a reviewer assume
  the grant was exact.
* `network=None` means this profile emits no VPC, subnet or firewall. The
  target then writes a `network.tf` stating that the isolation was **not**
  generated, rather than leaving a reader to assume it was (ADR-0084).
* `boundary_coarser_than_model` is where the tenant boundary is blunter than
  one tenant per blast radius (ADR-0050).

Declaring a weakness is not a defect in the profile — it is the profile doing
its job. A provider that quietly claimed full granularity would produce a
mapping report that reads as enforced and is not (ADR-0073).
"""
from __future__ import annotations

from orgagents.compiler.targets.terraform import ProviderProfile

#: Acme's private OpenStack cloud.
ACME_CLOUD = ProviderProfile(
    id="acme_cloud",
    display="Acme Private Cloud (OpenStack)",
    terraform_provider="openstack",
    source="terraform-provider-openstack/openstack",
    version="~> 3.0",
    resources={
        "compute_service": "openstack_compute_instance_v2",
        "job_runner": "openstack_compute_instance_v2",
        "state_store": "openstack_db_instance_v1",
        "object_store": "openstack_objectstorage_container_v1",
        "message_bus": "openstack_messaging_queue_v2",
        "observability_sink": "openstack_logging_project_sink",
        "network_boundary": "openstack_networking_network_v2",
        "scheduler": "openstack_compute_instance_v2",
        "channel_bridge": "openstack_compute_instance_v2",
        "memory_store": "openstack_db_instance_v1",
        # Deliberately absent: knowledge_index, event_subscription,
        # agent_endpoint. A resource this cloud has no equivalent for is left
        # out, and MAPPING.md lists it under "Unmapped neutral resources" —
        # which is more useful than mapping it onto something that is not it.
    },
    identity_resource="openstack_identity_user_v3",
    binding_resource="openstack_identity_role_assignment_v3",
    secret_resource="openstack_keymanager_secret_v1",
    region_variable="region",
    # Keystone roles are project-scoped and coarse: there is no per-resource
    # approval right, so an `approve` or `administer` grant lands wider than
    # the design asked for. Named here so MAPPING.md can flag every one.
    coarse_actions=("approve", "administer"),
    # A profile that ships in a plugin carries its own IAM mapping: the
    # built-in table inside orgagents cannot know about Acme's Keystone roles
    # (ADR-0091). Several neutral actions collapse onto `member` here, which
    # is exactly what `coarse_actions` above is declaring.
    action_roles={
        "read": "reader",
        "query": "reader",
        "write": "member",
        "invoke": "member",
        "publish": "member",
        "delegate": "member",
        "approve": "member",        # coarser than asked: see coarse_actions
        "administer": "admin",      # coarser than asked
    },
    # No network profile: this target will not generate a VPC, subnets or
    # firewall rules for Acme's cloud, and says so plainly rather than
    # implying the placement isolation was applied.
    network=None,
    boundary_kind="project",
    boundary_argument="tenant_id",
    boundary_enforcement=(
        "one Keystone **project** per tenant, pinned by the provider's "
        "`tenant_id`; every role assignment is scoped to that project"
    ),
    boundary_coarser_than_model=(
        "Keystone role assignments are project-scoped, so an identity reaches "
        "every resource of that kind in its own tenant's project. Network "
        "isolation between placements is NOT generated by this profile: "
        "Acme's platform team applies security groups out of band, and "
        "nothing here verifies that they did."
    ),
)


def register() -> None:
    """Add Acme's cloud to the Terraform target.

    Called by a host that wires plugins by hand; an installed distribution has
    this discovered through the `orgagents.provider_profiles` entry point
    instead.
    """
    from orgagents.compiler.base import REGISTRY, register_builtin_targets
    from orgagents.compiler.targets.terraform import (
        PROFILES,
        TerraformTarget,
        register_provider_profile,
    )

    if ACME_CLOUD.id not in PROFILES:
        register_provider_profile(ACME_CLOUD)
    register_builtin_targets()
    REGISTRY.register(TerraformTarget(ACME_CLOUD.id), replace=True)
