-- Migration 0002: data_class_schema_ref
-- Generated by `orgagents db generate-migration` from the UML profiles (ADR-0113). Forward-only; do not edit.
ALTER TABLE "data"."data_class" ADD COLUMN "schema_ref" text;
