"""Forward-only migrations of the relational schema (ADR-0113, ADR-0042).

The files beside this module are the history: `NNNN_<name>.sql`, applied in
order, and `schema.json`, the structure the last of them leaves. A new one is
never written by hand: `orgagents db generate-migration <name>` diffs
`schema.json` against the structure the profiles generate now and writes the
statements that take one to the other. `apply()` runs whatever a database
has not yet run, under an advisory lock so two starting designers do not
race, and records each file with its checksum.
"""
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Any, Optional

HERE = Path(__file__).resolve().parent
SNAPSHOT = HERE / "schema.json"
LEDGER = "public.orgagents_migrations"
#: Any constant, the same for every designer: serialises migration runs.
LOCK_KEY = 1130113

_NAME = re.compile(r"^(\d{4})_[a-z0-9_]+\.sql$")


def committed() -> list[Path]:
    return sorted(p for p in HERE.glob("*.sql") if _NAME.match(p.name))


def checksum(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def snapshot() -> Optional[dict[str, Any]]:
    if not SNAPSHOT.is_file():
        return None
    return json.loads(SNAPSHOT.read_text(encoding="utf-8"))


def pending_statements() -> list[str]:
    """What a new migration would hold: the committed snapshot against the
    structure the profiles generate now. Empty when they agree."""
    from ..relational import diff, structure
    return diff(snapshot(), structure())


def generate(name: str) -> Optional[Path]:
    """Write the next migration, or return None when nothing changed."""
    from ..relational import structure, structure_json
    statements = pending_statements()
    if not statements:
        return None
    slug = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_") or "change"
    number = len(committed()) + 1
    path = HERE / f"{number:04d}_{slug}.sql"
    header = (f"-- Migration {number:04d}: {name}\n"
              "-- Generated by `orgagents db generate-migration` from the "
              "UML profiles (ADR-0113). Forward-only; do not edit.\n")
    body = "\n".join(statements)
    path.write_text(header + body + ("" if body.endswith("\n") else "\n"),
                    encoding="utf-8", newline="\n")
    SNAPSHOT.write_text(structure_json(structure()), encoding="utf-8",
                        newline="\n")
    return path


def apply(connection: Any) -> list[str]:
    """Apply every committed migration the database has not run, in one
    transaction per call. `connection` is a SQLAlchemy Connection inside a
    transaction. Returns the names applied."""
    from sqlalchemy import text
    connection.execute(text("SELECT pg_advisory_xact_lock(:k)"),
                       {"k": LOCK_KEY})
    connection.execute(text(
        f"CREATE TABLE IF NOT EXISTS {LEDGER} ("
        "name text PRIMARY KEY, checksum text NOT NULL, "
        "applied_at timestamptz NOT NULL DEFAULT now())"))
    done = {r[0]: r[1] for r in connection.execute(
        text(f"SELECT name, checksum FROM {LEDGER}"))}
    applied = []
    for path in committed():
        if path.name in done:
            if done[path.name] != checksum(path):
                raise RuntimeError(
                    f"migration {path.name} was changed after it was "
                    f"applied; migrations are forward-only")
            continue
        run_script(connection, path.read_text(encoding="utf-8"))
        connection.execute(
            text(f"INSERT INTO {LEDGER} (name, checksum) VALUES (:n, :c)"),
            {"n": path.name, "c": checksum(path)})
        applied.append(path.name)
    return applied


def run_script(connection: Any, sql: str) -> None:
    """Run a multi-statement script on the connection's own transaction."""
    raw = connection.connection.driver_connection
    with raw.cursor() as cur:
        cur.execute(sql)
